# Generated by Django 5.1.3 on 2024-11-09 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.RemoveField(
            model_name='question',
            name='attachments',
        ),
        migrations.AddField(
            model_name='emailverification',
            name='expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='main_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.maintopic'),
        ),
        migrations.CreateModel(
            name='SubTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('main_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='core.maintopic')),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='sub_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subtopic'),
        ),
    ]
