# Generated by Django 5.1.3 on 2024-11-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_maintopic_alter_question_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverification',
            name='expired',
        ),
        migrations.AddField(
            model_name='emailverification',
            name='expiration_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
