# Generated by Django 5.1.3 on 2024-11-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_user_is_teacher_studentprofile_teacherprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/defaultAvatar.png', null=True, upload_to='profile_pictures/'),
        ),
    ]
